import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import * as schema from './schema';

// ─── Connection ──────────────────────────────────────────────────────────────

// DATABASE_PATH defaults to src/lib/db/data/skullboard.db (relative to process.cwd()).
// Override via the DATABASE_PATH environment variable.
const dbPath = process.env.DATABASE_PATH ?? join(process.cwd(), 'src', 'lib', 'db', 'data', 'skullboard.db');

// Ensure the parent directory exists before opening the file.
mkdirSync(dirname(dbPath), { recursive: true });

const sqlite = new Database(dbPath);
// WAL mode: better concurrent read performance.
sqlite.pragma('journal_mode = WAL');

export const db = drizzle(sqlite, { schema });

export type DrizzleDb = typeof db;

// ─── Auto-migrate ────────────────────────────────────────────────────────────

// Migrations live in src/lib/db/migrations/, generated by `pnpm db:generate`.
// process.cwd() is always the project root, which is stable for both dev and prod.
const migrationsFolder = join(process.cwd(), 'src', 'lib', 'db', 'migrations');
migrate(db, { migrationsFolder });

// ─── Future PostgreSQL migration path ────────────────────────────────────────
//
// When you are ready to switch to PostgreSQL:
//
//  1. Install the postgres.js driver:
//       pnpm add postgres
//       pnpm add -D @types/pg
//
//  2. Create a parallel schema file using pg-core:
//       src/lib/db/schema.pg.ts   (import from 'drizzle-orm/pg-core')
//
//  3. Update drizzle.config.ts:
//       dialect: 'postgresql'
//       schema:  './src/lib/db/schema.pg.ts'
//
//  4. Export a DATABASE_URL env var with a postgres:// connection string and
//     add it to the Env interface in setup.ts.
//
//  5. Replace this file's connection block with:
//
//       import { drizzle } from 'drizzle-orm/postgres-js';
//       import { migrate } from 'drizzle-orm/postgres-js/migrator';
//       import postgres    from 'postgres';
//       import * as schema from './schema.pg';
//
//       const sql  = postgres(process.env.DATABASE_URL!);
//       export const db = drizzle(sql, { schema });
//       await migrate(db, { migrationsFolder });   // note: async for PG
//
//  The rest of the codebase (container.db usage) is unaffected.
